// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestEntity.proto

package com.github.fashionbrot.common.entity;

public final class TestEntityProto {
  private TestEntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TestEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jinxing.hemu.protobuf.TestEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 parent_id = 3;</code>
     * @return The parentId.
     */
    long getParentId();

    /**
     * <code>string parent_name = 4;</code>
     * @return The parentName.
     */
    java.lang.String getParentName();
    /**
     * <code>string parent_name = 4;</code>
     * @return The bytes for parentName.
     */
    com.google.protobuf.ByteString
        getParentNameBytes();

    /**
     * <code>int64 test5 = 5;</code>
     * @return The test5.
     */
    long getTest5();

    /**
     * <code>int64 test6 = 6;</code>
     * @return The test6.
     */
    long getTest6();

    /**
     * <code>string test7 = 7;</code>
     * @return The test7.
     */
    java.lang.String getTest7();
    /**
     * <code>string test7 = 7;</code>
     * @return The bytes for test7.
     */
    com.google.protobuf.ByteString
        getTest7Bytes();

    /**
     * <code>int64 test8 = 8;</code>
     * @return The test8.
     */
    long getTest8();

    /**
     * <code>int64 test9 = 9;</code>
     * @return The test9.
     */
    long getTest9();

    /**
     * <code>string test10 = 10;</code>
     * @return The test10.
     */
    java.lang.String getTest10();
    /**
     * <code>string test10 = 10;</code>
     * @return The bytes for test10.
     */
    com.google.protobuf.ByteString
        getTest10Bytes();
  }
  /**
   * Protobuf type {@code com.jinxing.hemu.protobuf.TestEntity}
   */
  public static final class TestEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jinxing.hemu.protobuf.TestEntity)
      TestEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestEntity.newBuilder() to construct.
    private TestEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestEntity() {
      name_ = "";
      parentName_ = "";
      test7_ = "";
      test10_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestEntity();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TestEntity(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              parentId_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              parentName_ = s;
              break;
            }
            case 40: {

              test5_ = input.readInt64();
              break;
            }
            case 48: {

              test6_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              test7_ = s;
              break;
            }
            case 64: {

              test8_ = input.readInt64();
              break;
            }
            case 72: {

              test9_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              test10_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.fashionbrot.common.entity.TestEntityProto.internal_static_com_jinxing_hemu_protobuf_TestEntity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.fashionbrot.common.entity.TestEntityProto.internal_static_com_jinxing_hemu_protobuf_TestEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.class, com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARENT_ID_FIELD_NUMBER = 3;
    private long parentId_;
    /**
     * <code>int64 parent_id = 3;</code>
     * @return The parentId.
     */
    @java.lang.Override
    public long getParentId() {
      return parentId_;
    }

    public static final int PARENT_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object parentName_;
    /**
     * <code>string parent_name = 4;</code>
     * @return The parentName.
     */
    @java.lang.Override
    public java.lang.String getParentName() {
      java.lang.Object ref = parentName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentName_ = s;
        return s;
      }
    }
    /**
     * <code>string parent_name = 4;</code>
     * @return The bytes for parentName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getParentNameBytes() {
      java.lang.Object ref = parentName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST5_FIELD_NUMBER = 5;
    private long test5_;
    /**
     * <code>int64 test5 = 5;</code>
     * @return The test5.
     */
    @java.lang.Override
    public long getTest5() {
      return test5_;
    }

    public static final int TEST6_FIELD_NUMBER = 6;
    private long test6_;
    /**
     * <code>int64 test6 = 6;</code>
     * @return The test6.
     */
    @java.lang.Override
    public long getTest6() {
      return test6_;
    }

    public static final int TEST7_FIELD_NUMBER = 7;
    private volatile java.lang.Object test7_;
    /**
     * <code>string test7 = 7;</code>
     * @return The test7.
     */
    @java.lang.Override
    public java.lang.String getTest7() {
      java.lang.Object ref = test7_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test7_ = s;
        return s;
      }
    }
    /**
     * <code>string test7 = 7;</code>
     * @return The bytes for test7.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTest7Bytes() {
      java.lang.Object ref = test7_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test7_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST8_FIELD_NUMBER = 8;
    private long test8_;
    /**
     * <code>int64 test8 = 8;</code>
     * @return The test8.
     */
    @java.lang.Override
    public long getTest8() {
      return test8_;
    }

    public static final int TEST9_FIELD_NUMBER = 9;
    private long test9_;
    /**
     * <code>int64 test9 = 9;</code>
     * @return The test9.
     */
    @java.lang.Override
    public long getTest9() {
      return test9_;
    }

    public static final int TEST10_FIELD_NUMBER = 10;
    private volatile java.lang.Object test10_;
    /**
     * <code>string test10 = 10;</code>
     * @return The test10.
     */
    @java.lang.Override
    public java.lang.String getTest10() {
      java.lang.Object ref = test10_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        test10_ = s;
        return s;
      }
    }
    /**
     * <code>string test10 = 10;</code>
     * @return The bytes for test10.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTest10Bytes() {
      java.lang.Object ref = test10_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        test10_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (parentId_ != 0L) {
        output.writeInt64(3, parentId_);
      }
      if (!getParentNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parentName_);
      }
      if (test5_ != 0L) {
        output.writeInt64(5, test5_);
      }
      if (test6_ != 0L) {
        output.writeInt64(6, test6_);
      }
      if (!getTest7Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, test7_);
      }
      if (test8_ != 0L) {
        output.writeInt64(8, test8_);
      }
      if (test9_ != 0L) {
        output.writeInt64(9, test9_);
      }
      if (!getTest10Bytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, test10_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (parentId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, parentId_);
      }
      if (!getParentNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parentName_);
      }
      if (test5_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, test5_);
      }
      if (test6_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, test6_);
      }
      if (!getTest7Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, test7_);
      }
      if (test8_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, test8_);
      }
      if (test9_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, test9_);
      }
      if (!getTest10Bytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, test10_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.fashionbrot.common.entity.TestEntityProto.TestEntity)) {
        return super.equals(obj);
      }
      com.github.fashionbrot.common.entity.TestEntityProto.TestEntity other = (com.github.fashionbrot.common.entity.TestEntityProto.TestEntity) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getParentId()
          != other.getParentId()) return false;
      if (!getParentName()
          .equals(other.getParentName())) return false;
      if (getTest5()
          != other.getTest5()) return false;
      if (getTest6()
          != other.getTest6()) return false;
      if (!getTest7()
          .equals(other.getTest7())) return false;
      if (getTest8()
          != other.getTest8()) return false;
      if (getTest9()
          != other.getTest9()) return false;
      if (!getTest10()
          .equals(other.getTest10())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + PARENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getParentId());
      hash = (37 * hash) + PARENT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getParentName().hashCode();
      hash = (37 * hash) + TEST5_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTest5());
      hash = (37 * hash) + TEST6_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTest6());
      hash = (37 * hash) + TEST7_FIELD_NUMBER;
      hash = (53 * hash) + getTest7().hashCode();
      hash = (37 * hash) + TEST8_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTest8());
      hash = (37 * hash) + TEST9_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTest9());
      hash = (37 * hash) + TEST10_FIELD_NUMBER;
      hash = (53 * hash) + getTest10().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.fashionbrot.common.entity.TestEntityProto.TestEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jinxing.hemu.protobuf.TestEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jinxing.hemu.protobuf.TestEntity)
        com.github.fashionbrot.common.entity.TestEntityProto.TestEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.fashionbrot.common.entity.TestEntityProto.internal_static_com_jinxing_hemu_protobuf_TestEntity_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.fashionbrot.common.entity.TestEntityProto.internal_static_com_jinxing_hemu_protobuf_TestEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.class, com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.Builder.class);
      }

      // Construct using com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        parentId_ = 0L;

        parentName_ = "";

        test5_ = 0L;

        test6_ = 0L;

        test7_ = "";

        test8_ = 0L;

        test9_ = 0L;

        test10_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.fashionbrot.common.entity.TestEntityProto.internal_static_com_jinxing_hemu_protobuf_TestEntity_descriptor;
      }

      @java.lang.Override
      public com.github.fashionbrot.common.entity.TestEntityProto.TestEntity getDefaultInstanceForType() {
        return com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.fashionbrot.common.entity.TestEntityProto.TestEntity build() {
        com.github.fashionbrot.common.entity.TestEntityProto.TestEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.fashionbrot.common.entity.TestEntityProto.TestEntity buildPartial() {
        com.github.fashionbrot.common.entity.TestEntityProto.TestEntity result = new com.github.fashionbrot.common.entity.TestEntityProto.TestEntity(this);
        result.id_ = id_;
        result.name_ = name_;
        result.parentId_ = parentId_;
        result.parentName_ = parentName_;
        result.test5_ = test5_;
        result.test6_ = test6_;
        result.test7_ = test7_;
        result.test8_ = test8_;
        result.test9_ = test9_;
        result.test10_ = test10_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.fashionbrot.common.entity.TestEntityProto.TestEntity) {
          return mergeFrom((com.github.fashionbrot.common.entity.TestEntityProto.TestEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.fashionbrot.common.entity.TestEntityProto.TestEntity other) {
        if (other == com.github.fashionbrot.common.entity.TestEntityProto.TestEntity.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getParentId() != 0L) {
          setParentId(other.getParentId());
        }
        if (!other.getParentName().isEmpty()) {
          parentName_ = other.parentName_;
          onChanged();
        }
        if (other.getTest5() != 0L) {
          setTest5(other.getTest5());
        }
        if (other.getTest6() != 0L) {
          setTest6(other.getTest6());
        }
        if (!other.getTest7().isEmpty()) {
          test7_ = other.test7_;
          onChanged();
        }
        if (other.getTest8() != 0L) {
          setTest8(other.getTest8());
        }
        if (other.getTest9() != 0L) {
          setTest9(other.getTest9());
        }
        if (!other.getTest10().isEmpty()) {
          test10_ = other.test10_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.fashionbrot.common.entity.TestEntityProto.TestEntity parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.fashionbrot.common.entity.TestEntityProto.TestEntity) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long parentId_ ;
      /**
       * <code>int64 parent_id = 3;</code>
       * @return The parentId.
       */
      @java.lang.Override
      public long getParentId() {
        return parentId_;
      }
      /**
       * <code>int64 parent_id = 3;</code>
       * @param value The parentId to set.
       * @return This builder for chaining.
       */
      public Builder setParentId(long value) {
        
        parentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 parent_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentId() {
        
        parentId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object parentName_ = "";
      /**
       * <code>string parent_name = 4;</code>
       * @return The parentName.
       */
      public java.lang.String getParentName() {
        java.lang.Object ref = parentName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          parentName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string parent_name = 4;</code>
       * @return The bytes for parentName.
       */
      public com.google.protobuf.ByteString
          getParentNameBytes() {
        java.lang.Object ref = parentName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          parentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string parent_name = 4;</code>
       * @param value The parentName to set.
       * @return This builder for chaining.
       */
      public Builder setParentName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        parentName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string parent_name = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearParentName() {
        
        parentName_ = getDefaultInstance().getParentName();
        onChanged();
        return this;
      }
      /**
       * <code>string parent_name = 4;</code>
       * @param value The bytes for parentName to set.
       * @return This builder for chaining.
       */
      public Builder setParentNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        parentName_ = value;
        onChanged();
        return this;
      }

      private long test5_ ;
      /**
       * <code>int64 test5 = 5;</code>
       * @return The test5.
       */
      @java.lang.Override
      public long getTest5() {
        return test5_;
      }
      /**
       * <code>int64 test5 = 5;</code>
       * @param value The test5 to set.
       * @return This builder for chaining.
       */
      public Builder setTest5(long value) {
        
        test5_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 test5 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest5() {
        
        test5_ = 0L;
        onChanged();
        return this;
      }

      private long test6_ ;
      /**
       * <code>int64 test6 = 6;</code>
       * @return The test6.
       */
      @java.lang.Override
      public long getTest6() {
        return test6_;
      }
      /**
       * <code>int64 test6 = 6;</code>
       * @param value The test6 to set.
       * @return This builder for chaining.
       */
      public Builder setTest6(long value) {
        
        test6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 test6 = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest6() {
        
        test6_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object test7_ = "";
      /**
       * <code>string test7 = 7;</code>
       * @return The test7.
       */
      public java.lang.String getTest7() {
        java.lang.Object ref = test7_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test7_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test7 = 7;</code>
       * @return The bytes for test7.
       */
      public com.google.protobuf.ByteString
          getTest7Bytes() {
        java.lang.Object ref = test7_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test7_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test7 = 7;</code>
       * @param value The test7 to set.
       * @return This builder for chaining.
       */
      public Builder setTest7(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test7 = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest7() {
        
        test7_ = getDefaultInstance().getTest7();
        onChanged();
        return this;
      }
      /**
       * <code>string test7 = 7;</code>
       * @param value The bytes for test7 to set.
       * @return This builder for chaining.
       */
      public Builder setTest7Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test7_ = value;
        onChanged();
        return this;
      }

      private long test8_ ;
      /**
       * <code>int64 test8 = 8;</code>
       * @return The test8.
       */
      @java.lang.Override
      public long getTest8() {
        return test8_;
      }
      /**
       * <code>int64 test8 = 8;</code>
       * @param value The test8 to set.
       * @return This builder for chaining.
       */
      public Builder setTest8(long value) {
        
        test8_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 test8 = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest8() {
        
        test8_ = 0L;
        onChanged();
        return this;
      }

      private long test9_ ;
      /**
       * <code>int64 test9 = 9;</code>
       * @return The test9.
       */
      @java.lang.Override
      public long getTest9() {
        return test9_;
      }
      /**
       * <code>int64 test9 = 9;</code>
       * @param value The test9 to set.
       * @return This builder for chaining.
       */
      public Builder setTest9(long value) {
        
        test9_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 test9 = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest9() {
        
        test9_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object test10_ = "";
      /**
       * <code>string test10 = 10;</code>
       * @return The test10.
       */
      public java.lang.String getTest10() {
        java.lang.Object ref = test10_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          test10_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string test10 = 10;</code>
       * @return The bytes for test10.
       */
      public com.google.protobuf.ByteString
          getTest10Bytes() {
        java.lang.Object ref = test10_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          test10_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string test10 = 10;</code>
       * @param value The test10 to set.
       * @return This builder for chaining.
       */
      public Builder setTest10(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        test10_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string test10 = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearTest10() {
        
        test10_ = getDefaultInstance().getTest10();
        onChanged();
        return this;
      }
      /**
       * <code>string test10 = 10;</code>
       * @param value The bytes for test10 to set.
       * @return This builder for chaining.
       */
      public Builder setTest10Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        test10_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jinxing.hemu.protobuf.TestEntity)
    }

    // @@protoc_insertion_point(class_scope:com.jinxing.hemu.protobuf.TestEntity)
    private static final com.github.fashionbrot.common.entity.TestEntityProto.TestEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.fashionbrot.common.entity.TestEntityProto.TestEntity();
    }

    public static com.github.fashionbrot.common.entity.TestEntityProto.TestEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestEntity>
        PARSER = new com.google.protobuf.AbstractParser<TestEntity>() {
      @java.lang.Override
      public TestEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TestEntity(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TestEntity> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestEntity> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.fashionbrot.common.entity.TestEntityProto.TestEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jinxing_hemu_protobuf_TestEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jinxing_hemu_protobuf_TestEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TestEntity.proto\022\031com.jinxing.hemu.pro" +
      "tobuf\"\251\001\n\nTestEntity\022\n\n\002id\030\001 \001(\003\022\014\n\004name" +
      "\030\002 \001(\t\022\021\n\tparent_id\030\003 \001(\003\022\023\n\013parent_name" +
      "\030\004 \001(\t\022\r\n\005test5\030\005 \001(\003\022\r\n\005test6\030\006 \001(\003\022\r\n\005" +
      "test7\030\007 \001(\t\022\r\n\005test8\030\010 \001(\003\022\r\n\005test9\030\t \001(" +
      "\003\022\016\n\006test10\030\n \001(\tB7\n$com.github.fashionb" +
      "rot.common.entityB\017TestEntityProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_jinxing_hemu_protobuf_TestEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jinxing_hemu_protobuf_TestEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jinxing_hemu_protobuf_TestEntity_descriptor,
        new java.lang.String[] { "Id", "Name", "ParentId", "ParentName", "Test5", "Test6", "Test7", "Test8", "Test9", "Test10", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
